FROM flink:1.17.2-java11

COPY src/main/resources/log4j.properties /opt/flink/conf/log4j.properties
COPY src/main/resources/log4j-console.properties /opt/flink/conf/log4j-console.properties
COPY src/main/resources/log4j-cli.properties /opt/flink/conf/log4j-cli.properties